// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import NavBar from './Components/Navbar'
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NavBar/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
